name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/woodez-website:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/woodez-website:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/woodez-website:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/woodez-website:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/woodez-website:latest
